### ISSUE TITLE
get working on linux-32, python 2.7

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Platform/nb_conda#10]
Follow-on to #9 and #8.

**Comment by damianavila** [comment]
:star2:

**Comment by damianavila** [comment]
This is probably because there is some missing dependencies... there is a bug in Anaconda Server preventing upload packages from this combination... the bug was fixed and will be deployed in the next release, so this will desappear after that...

**Comment by damianavila** [comment]
We are building in conda-forge and conda-forge does not support linux32 pacakges, so closing this one now.
