### ISSUE TITLE
Clicking a Conda environment doesn't display installed packages

### ISSUE THREAD

**Issue by vroomanj** [Anaconda-Platform/nb_conda#30]
I am running nb_conda 2.0.0 and when I click on an existing and/or newly created Conda environment it does not list the installed packages nor allow me to install packages. All of the Conda environments seem to link to: http://url.com/tree#

What more information can I provide to help resolve this issue?

**Comment by damianavila** [comment]
Can you provide your platform and how did you get nb_conda (from Anaconda? installed from source? anaconda-nb-extensions channel? another way?)

Also please post your `jupyter nbextension list` and `jupyter serverextension list`

Thanks!

**Comment by vroomanj** [comment]
@damianavila I resolved this issue by upgrading Jupyter... I can recreate it and get you this information but I'm not sure it is worth it.

**Comment by damianavila** [comment]
I agree... if you see the issue again don't hesitate to comment on this issue. Cheers.

**Comment by MayankShah1** [comment]
I'm facing this same problem, it is showing Internal server error when i open this Conda tab.
When i installed my conda, it was working correctly but when I did ```conda update --all``` its showing error.
this is my ```jupyter nbextension list``` output 
Known nbextensions:
  config dir: /home/mayank/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK
and ```jupyter serverextension list```
config dir: /home/mayank/anaconda3/etc/jupyter
    nb_conda  enabled 
    - Validating...
      nb_conda  OK
    nbpresent  enabled 
    - Validating...
      nbpresent  OK
    nb_anacondacloud  enabled 
    - Validating...
      nb_anacondacloud  OK

**Comment by damianavila** [comment]
>When i installed my conda, it was working correctly

What do you mean, when you installed Anaconda?

> but when I did conda update --all its showing error.

notebook and nb_conda versions? anything in the js console?
