### ISSUE TITLE
Displaying Python [Root] as Python 3?

### ISSUE THREAD

**Issue by vroomanj** [Anaconda-Platform/nb_conda#32]
Is it possible to display "Python [Root]" as "Python 3" using nb_conda? Python [Root] breaks notebooks that were built using the Python 3 environment requiring the kernel to be changed (which isn't a huge deal but one the professors I am working with would prefer not to have to introduce causing more confusion).

**Comment by damianavila** [comment]
This is fact a nb_conda_kernels question... right now with the latest nb_conda_kernels version, you should see a `[Python default]` environment which is using the Native python kernel, so a notebook created without the extension with the `Python 3` kernel will be opened as the `Python[default]` without issues.
If you have further problems, let me know. Closing for now.
