### ISSUE TITLE
Confused by multiple kernels in same environment

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_conda#33]
I have a SAS kernel installed in my AEN project environment.  It is just another kernel that is part of the "default" environment.  But it seems to confuse `nb_conda`:

<img width="687" alt="screen shot 2016-09-15 at 6 37 18 pm" src="https://cloud.githubusercontent.com/assets/293525/18569940/35f199da-7b74-11e6-89de-c88f505fa516.png">

Here is the text:

```
Error: environment does not exist: /projects/guest/Demo_SAS_kernel/envs/sas # # Use 'conda create' to create an environment before listing its packages.
```

**Comment by damianavila** [comment]
Where do you have the kernel installed? Or how do you install it? It would be nice more info to know about what could be the potential conflict...

**Comment by damianavila** [comment]
Closing as stale, if you can provide more info, I will be happy to re-open it. Cheers.
