### ISSUE TITLE
compile and test to support python 3.6 and upload to anaconda.org/

### ISSUE THREAD

**Issue by cailiang9** [Anaconda-Platform/nb_conda#45]

**Comment by damianavila** [comment]
Hopefully this will be done in the next few weeks.

**Comment by basnijholt** [comment]
It would be great if you could look at the `conda-forge` feedstock too.

I've tried to get it to work in [this PR](https://github.com/conda-forge/nb_conda-feedstock/pull/5), but failed.

**Comment by ginkgo-brandeis** [comment]
any updates on python3.6 support?

**Comment by damianavila** [comment]
Hopefully soon.

**Comment by damianavila** [comment]
Everyone, last release nb_conda 2.2.0 is already built and available in conda-forge including py3.6 support.
Closing now.

**Comment by damianavila** [comment]
Btw, conda packages from `defaults` channel will be available soon.
