### ISSUE TITLE
Tests not working for master

### ISSUE THREAD

**Issue by basnijholt** [Anaconda-Platform/nb_conda#47]
In the [`.travis.yml`](https://github.com/Anaconda-Platform/nb_conda/blob/master/.travis.yml#L31) I find the following:

`conda install -n nb_conda -c conda-forge --file requirements.txt `

This means that the tests do not really mean anything for master.

**Comment by damianavila** [comment]
> This means that the tests do not really mean anything for master.

This line should do the test trick, I think... https://github.com/Anaconda-Platform/nb_conda/blob/master/.travis.yml#L41

**Comment by basnijholt** [comment]
Yes, you are completely right, I misread the CI file, I thought it was installing the version from `conda-forge` instead of from the repo.
