### ISSUE TITLE
Python 3 Build on conda-forge?

### ISSUE THREAD

**Issue by rbhatia5** [Anaconda-Platform/nb_conda#55]
Is there an expectation that someone will push a build of 2.2 targeting python 3.x? I see python2.7 builds on conda-forge and am trying to decide between building myself and installing or just waiting for a build to hit conda-forge?

**Comment by damianavila** [comment]
There are python 3.x build on conda-forge: https://anaconda.org/conda-forge/nb_conda/files?version=2.2.0
