### ISSUE TITLE
in envmanager.py  'dict' object has no attribute 'resplit'

### ISSUE THREAD

**Issue by strange-jiong** [Anaconda-Platform/nb_conda#64]
line 23 in envmanager.py.

should it be 'split'?

**Comment by damianavila** [comment]
Which conda version and nb_conda version do you have installed?

**Comment by strange-jiong** [comment]
conda 4.3.29
nb_conda 2.0.0

**Comment by damianavila** [comment]
Please upgrade to the lastest `nb_conda` version: 2.2.1. Thanks!

**Comment by strange-jiong** [comment]
I know，thanks
