### ISSUE TITLE
Get building locally on Windows-64, Python 3.5

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Platform/nb_conda#8]
https://anaconda.org/anaconda-nb-extensions/nb_conda/builds/5/14

```batch
391WARNING:root:Environment name starts with underscore '_'.  Skipping menu installation.

392

393C:\Users\binstar\builds\anaconda-nb-extensions\nb_conda\source>"C:\Users\binstar\Miniconda\envs\_test\bin\python" -m nb_conda.setup install --enable --prefix="C:\Users\binstar\Miniconda\envs\_test" 

394The system cannot find the path specified.

395Error: post-link failed for: nb_conda-0.1.2-py35_0_g4fda71b

396Exit BINSTAR_BUILD_RESULT=failure
```

**Comment by bollwyvl** [comment]
When trying to install nb_conda_kernels, getting the "application wasn't able to start" dialog! :skull: investigating.

<img width="1440" alt="screen shot 2016-01-29 at 5 23 02 pm" src="https://cloud.githubusercontent.com/assets/45380/12689781/01d9043e-c6ad-11e5-97cd-c1fc6484b558.png">

**Comment by msarahan** [comment]
Those are often related to runtimes not being installed correctly.  There is a known issue right now where that happens if python version is not explicitly specified when creating the env.  Can you post your env creation line?

**Comment by bollwyvl** [comment]
i created a new user and am getting further... will update.
